// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8U7EL3F0-ihhxVsCGm6sUm0iWEWjZyTQ',
    appId: '1:954214301039:web:49af42e5d81c15f5ecbc9a',
    messagingSenderId: '954214301039',
    projectId: 'massive-vector-501914-a5',
    authDomain: 'massive-vector-501914-a5.firebaseapp.com',
    storageBucket: 'massive-vector-501914-a5.firebasestorage.app',
    measurementId: 'G-KX6679E6EX',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6wdeQ_AsPOhQN5pKtBjOtMqcr8bMWQEg',
    appId: '1:954214301039:ios:3a2772813670a021ecbc9a',
    messagingSenderId: '954214301039',
    projectId: 'massive-vector-501914-a5',
    storageBucket: 'massive-vector-501914-a5.firebasestorage.app',
    androidClientId: '954214301039-qvgpgp6ttgj3uus1p8kugfaa8gamfprb.apps.googleusercontent.com',
    iosClientId: '954214301039-t7tvo7h1denqb7mdhg832etpsaop9ni5.apps.googleusercontent.com',
    iosBundleId: 'com.example.mailmindFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8U7EL3F0-ihhxVsCGm6sUm0iWEWjZyTQ',
    appId: '1:954214301039:web:26fed76766e661b6ecbc9a',
    messagingSenderId: '954214301039',
    projectId: 'massive-vector-501914-a5',
    authDomain: 'massive-vector-501914-a5.firebaseapp.com',
    storageBucket: 'massive-vector-501914-a5.firebasestorage.app',
    measurementId: 'G-8LYRVPLC1P',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6wdeQ_AsPOhQN5pKtBjOtMqcr8bMWQEg',
    appId: '1:954214301039:ios:3a2772813670a021ecbc9a',
    messagingSenderId: '954214301039',
    projectId: 'massive-vector-501914-a5',
    storageBucket: 'massive-vector-501914-a5.firebasestorage.app',
    androidClientId: '954214301039-qvgpgp6ttgj3uus1p8kugfaa8gamfprb.apps.googleusercontent.com',
    iosClientId: '954214301039-t7tvo7h1denqb7mdhg832etpsaop9ni5.apps.googleusercontent.com',
    iosBundleId: 'com.example.mailmindFrontend',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1nEx_mzUJ8W7ohIMves0i22roSvPTlnQ',
    appId: '1:954214301039:android:5bf90157e3307342ecbc9a',
    messagingSenderId: '954214301039',
    projectId: 'massive-vector-501914-a5',
    storageBucket: 'massive-vector-501914-a5.firebasestorage.app',
  );
}
