// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwjIrvFokuxRJG9ebjTk7jBNFd1H6-ehA',
    appId: '1:1019970178825:web:50e091065ec1954c5b0dd8',
    messagingSenderId: '1019970178825',
    projectId: 'mailmind-4ca8e',
    authDomain: 'mailmind-4ca8e.firebaseapp.com',
    storageBucket: 'mailmind-4ca8e.firebasestorage.app',
    measurementId: 'G-DCYXRK3J8K',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUhilpLISTUCObAkg68ZyZcKd46PzZ0qc',
    appId: '1:1019970178825:ios:368def3ca95528935b0dd8',
    messagingSenderId: '1019970178825',
    projectId: 'mailmind-4ca8e',
    storageBucket: 'mailmind-4ca8e.firebasestorage.app',
    iosClientId: '1019970178825-5bh5b4a405agjcmsld8iookldbhpmo7b.apps.googleusercontent.com',
    iosBundleId: 'com.example.mailmindFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwjIrvFokuxRJG9ebjTk7jBNFd1H6-ehA',
    appId: '1:1019970178825:web:50e091065ec1954c5b0dd8',
    messagingSenderId: '1019970178825',
    projectId: 'mailmind-4ca8e',
    authDomain: 'mailmind-4ca8e.firebaseapp.com',
    storageBucket: 'mailmind-4ca8e.firebasestorage.app',
    measurementId: 'G-DCYXRK3J8K',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUhilpLISTUCObAkg68ZyZcKd46PzZ0qc',
    appId: '1:1019970178825:ios:368def3ca95528935b0dd8',
    messagingSenderId: '1019970178825',
    projectId: 'mailmind-4ca8e',
    storageBucket: 'mailmind-4ca8e.firebasestorage.app',
    iosClientId: '1019970178825-5bh5b4a405agjcmsld8iookldbhpmo7b.apps.googleusercontent.com',
    iosBundleId: 'com.example.mailmindFrontend',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChMcS6KMmYVDVB71sSIKhooqyHbc4fgYo',
    appId: '1:1019970178825:android:157bfb38f72ddfff5b0dd8',
    messagingSenderId: '1019970178825',
    projectId: 'mailmind-4ca8e',
    storageBucket: 'mailmind-4ca8e.firebasestorage.app',
  );
}
